# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stefano/Coding/EasyGUI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stefano/Coding/EasyGUI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stefano/Coding/EasyGUI/CMakeFiles /home/stefano/Coding/EasyGUI//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stefano/Coding/EasyGUI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EGUI

# Build rule for target.
EGUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EGUI
.PHONY : EGUI

# fast build rule for target.
EGUI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/build
.PHONY : EGUI/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/EGUI_Colors.o: src/EGUI_Colors.cpp.o
.PHONY : src/EGUI_Colors.o

# target to build an object file
src/EGUI_Colors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Colors.cpp.o
.PHONY : src/EGUI_Colors.cpp.o

src/EGUI_Colors.i: src/EGUI_Colors.cpp.i
.PHONY : src/EGUI_Colors.i

# target to preprocess a source file
src/EGUI_Colors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Colors.cpp.i
.PHONY : src/EGUI_Colors.cpp.i

src/EGUI_Colors.s: src/EGUI_Colors.cpp.s
.PHONY : src/EGUI_Colors.s

# target to generate assembly for a file
src/EGUI_Colors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Colors.cpp.s
.PHONY : src/EGUI_Colors.cpp.s

src/EGUI_Rectangle.o: src/EGUI_Rectangle.cpp.o
.PHONY : src/EGUI_Rectangle.o

# target to build an object file
src/EGUI_Rectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Rectangle.cpp.o
.PHONY : src/EGUI_Rectangle.cpp.o

src/EGUI_Rectangle.i: src/EGUI_Rectangle.cpp.i
.PHONY : src/EGUI_Rectangle.i

# target to preprocess a source file
src/EGUI_Rectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Rectangle.cpp.i
.PHONY : src/EGUI_Rectangle.cpp.i

src/EGUI_Rectangle.s: src/EGUI_Rectangle.cpp.s
.PHONY : src/EGUI_Rectangle.s

# target to generate assembly for a file
src/EGUI_Rectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Rectangle.cpp.s
.PHONY : src/EGUI_Rectangle.cpp.s

src/EGUI_Shape.o: src/EGUI_Shape.cpp.o
.PHONY : src/EGUI_Shape.o

# target to build an object file
src/EGUI_Shape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Shape.cpp.o
.PHONY : src/EGUI_Shape.cpp.o

src/EGUI_Shape.i: src/EGUI_Shape.cpp.i
.PHONY : src/EGUI_Shape.i

# target to preprocess a source file
src/EGUI_Shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Shape.cpp.i
.PHONY : src/EGUI_Shape.cpp.i

src/EGUI_Shape.s: src/EGUI_Shape.cpp.s
.PHONY : src/EGUI_Shape.s

# target to generate assembly for a file
src/EGUI_Shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Shape.cpp.s
.PHONY : src/EGUI_Shape.cpp.s

src/EGUI_Widget.o: src/EGUI_Widget.cpp.o
.PHONY : src/EGUI_Widget.o

# target to build an object file
src/EGUI_Widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Widget.cpp.o
.PHONY : src/EGUI_Widget.cpp.o

src/EGUI_Widget.i: src/EGUI_Widget.cpp.i
.PHONY : src/EGUI_Widget.i

# target to preprocess a source file
src/EGUI_Widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Widget.cpp.i
.PHONY : src/EGUI_Widget.cpp.i

src/EGUI_Widget.s: src/EGUI_Widget.cpp.s
.PHONY : src/EGUI_Widget.s

# target to generate assembly for a file
src/EGUI_Widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Widget.cpp.s
.PHONY : src/EGUI_Widget.cpp.s

src/EGUI_Window.o: src/EGUI_Window.cpp.o
.PHONY : src/EGUI_Window.o

# target to build an object file
src/EGUI_Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Window.cpp.o
.PHONY : src/EGUI_Window.cpp.o

src/EGUI_Window.i: src/EGUI_Window.cpp.i
.PHONY : src/EGUI_Window.i

# target to preprocess a source file
src/EGUI_Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Window.cpp.i
.PHONY : src/EGUI_Window.cpp.i

src/EGUI_Window.s: src/EGUI_Window.cpp.s
.PHONY : src/EGUI_Window.s

# target to generate assembly for a file
src/EGUI_Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EGUI.dir/build.make CMakeFiles/EGUI.dir/src/EGUI_Window.cpp.s
.PHONY : src/EGUI_Window.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... EGUI"
	@echo "... main"
	@echo "... src/EGUI_Colors.o"
	@echo "... src/EGUI_Colors.i"
	@echo "... src/EGUI_Colors.s"
	@echo "... src/EGUI_Rectangle.o"
	@echo "... src/EGUI_Rectangle.i"
	@echo "... src/EGUI_Rectangle.s"
	@echo "... src/EGUI_Shape.o"
	@echo "... src/EGUI_Shape.i"
	@echo "... src/EGUI_Shape.s"
	@echo "... src/EGUI_Widget.o"
	@echo "... src/EGUI_Widget.i"
	@echo "... src/EGUI_Widget.s"
	@echo "... src/EGUI_Window.o"
	@echo "... src/EGUI_Window.i"
	@echo "... src/EGUI_Window.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

